"""initial migration create skill table

Revision ID: 0a54bfc6ea6e
Revises:
Create Date: 2025-07-31 18:22:27.381353

"""

from datetime import date
from typing import Sequence, Union

from alembic import op
from sqlmodel import Session, select
from src.core.database import create_db_and_tables
from src.skills.infrastructure.models import Skill



# revision identifiers, used by Alembic.
revision: str = "0a54bfc6ea6e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None




def upgrade() -> None:
    bind = op.get_bind()
    session = Session(bind=bind)
    """Upgrade schema."""
   # ### commands auto generated by Alembic - please adjust! ###
    table_obj=Skill.__table__ # type: ignore
    table_obj.create(bind=op.get_bind())
    create_db_and_tables()
    skills = [
        Skill(skill="Python", level=60, firstUsedDate=date(2022, 1, 1)),
        Skill(skill="HTML", level=70, firstUsedDate=date(2009, 1, 1)),
        Skill(skill="CSS/SCSS", level=70, firstUsedDate=date(2011, 1, 1)),
        Skill(skill="Tailwind CSS", level=10, firstUsedDate=date(2025, 3, 1)),
        Skill(skill="JavaScript", level=80, firstUsedDate=date(2011, 1, 1)),
        Skill(skill="TypeScript", level=80, firstUsedDate=date(2012, 1, 1)),
        Skill(skill="React", level=80, firstUsedDate=date(2018, 1, 1)),
        Skill(skill="Angular", level=80, firstUsedDate=date(2013, 1, 1)),
        Skill(skill="Express.js", level=80, firstUsedDate=date(2017, 1, 1)),
        Skill(skill="MongoDB", level=70, firstUsedDate=date(2017, 1, 1)),
        Skill(skill="PostgreSQL", level=70, firstUsedDate=date(2017, 1, 1)),
        Skill(skill="MySQL", level=70, firstUsedDate=date(2009, 1, 1)),
        Skill(skill="Bootstrap", level=80, firstUsedDate=date(2015, 1, 1)),
        Skill(skill="Git", level=80, firstUsedDate=date(2011, 1, 1)),
        Skill(skill="Domain Driven Design", level=75, firstUsedDate=date(2023, 1, 1)),
        Skill(skill="Photoshop", level=80, firstUsedDate=date(1999, 1, 1)),
        Skill(skill="Docker", level=30, firstUsedDate=date(2023, 1, 1)),
        Skill(skill="Microservices", level=70, firstUsedDate=date(2018, 1, 1)),
        Skill(skill="REST Services", level=70, firstUsedDate=date(2018, 1, 1)),
        Skill(skill="GraphQL", level=50, firstUsedDate=date(2022, 1, 1)),
        Skill(skill="UML", level=70, firstUsedDate=date(2009, 1, 1)),
        Skill(skill="Design Patterns", level=75, firstUsedDate=date(2018, 1, 1)),
        Skill(skill="OOP", level=90, firstUsedDate=date(2018, 1, 1)),
        Skill(skill="Android Development", level=50, firstUsedDate=date(2015, 1, 1)),
    ]
    session.add_all(skills)
    session.commit()


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    session = Session(bind=bind)
    statement = select(Skill)
    all_skills=session.exec(statement).all()
    for skill in all_skills:
        session.delete(skill)
    session.commit()
    table_object=Skill.__table__# type: ignore
    table_object.drop(bind=op.get_bind())
