"""initial migration create skill table

Revision ID: 0a54bfc6ea6e
Revises:
Create Date: 2025-07-31 18:22:27.381353

"""

from datetime import date
from typing import Literal, Sequence, TypeAlias, Union
from uuid import UUID

from alembic import op
from sqlmodel import Session, select
from src.core.database import create_db_and_tables
from src.education.infrastructure.models.education import Education
from src.language.infrastructure.models.language import Language
from src.professional_experience.infrastructure.models.professional_experience_model import (
    Company,
    CompanyType,
    ProfessionalExperience,
    Responsibility,
)
from src.profile.infrastructure.models.profile import Profile
from src.project.infrastructure.models.project import Project
from src.project.infrastructure.models.project_category_model import ProjectCategory
from src.skills.infrastructure.models import Skill
from src.tech_profile.infrastructure.models.tech_profile import TechProfile


# revision identifiers, used by Alembic.
revision: str = "0a54bfc6ea6e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

professional_experiences_key: TypeAlias = Literal[
    "cice_experience",
    "ehecatl_experience",
    "pizzapp_experience",
    "inidetam_experience",
    "tiempo_dev_experience",
    "three_pillar_gobal_experience",
    "independent_experience",
]
SkillNames: TypeAlias = Literal[
    "CI/CD",
    "Github Pages",
    "SQLModel",
    "Render",
    "TypeOrm",
    "dask",
    "alembic",
    "Prisma ORM",
    "Technical Support",
    "Ionic",
    "PHP",
    "Python",
    "HTML",
    "CSS/SCSS",
    "Tailwind CSS",
    "Javascript",
    "Typescript",
    "React",
    "Angular",
    "Express.js",
    "Node.js",
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "Bootstrap",
    "Git",
    "Domain Driven Design",
    "Photoshop",
    "Docker",
    "Microservices",
    "REST Services",
    "GraphQL",
    "UML",
    "Design Patterns",
    "OOP",
    "Android Development",
    "ActionScript 3.0",
    "FastAPI",
    "Django",
    "Testing",
    "Next.js",
    "NestJs",
    "Technical Documentation",
    "Firebase",
    "Supabase",
    "Github Actions",
    "UI/UX",
    "Azure",
    "DynamoDB",
    "AWS",
    "Wordpress",
    "Scrum",
    "Clean Architecture",
    "SOLID_principles",
    "Metaio framework",
    "Socket.io",
    "Adobe AIR",
    "Adobe Flex",
    "Adobe Illustrator",
    "Adobe InDesign",
    "Adobe Photoshop",
    "Robotlegs",
    "Java",
    "PhoneGap",
    "Cordova",
    "Yeoman",
    "Material Design",
    "Augmented Reality",
    "world_wind",
    "GIS",
    "event_driven_architecture",
    "Redux",
    "Kanban",
    "Pm2",
    "unit testing",
    "Postman",
    "Storybook",
    "Figma",
    "Jira",
    "RxJS Observables",
    "PySide6",
    "numpy",
    "matplotlib",
    "pandas",
]

project_keys: TypeAlias = Literal[
    "mobile-app-combustibles",
    'goKarts',
    'resume-api',
    "mobile-app-tarjado",
    "mobile-app-resumen-op",
    "app-rec-aduanero",
    "app-doc-approval",
    "app-contenedores",
    "app-live-in-tour",
    "app-echocalc",
    "app-hectorizate",
    "web-dictamen",
    "pizzap",
    "cesisccam",
    "cbt",
    "amps",
    "nielsen",
    "centene",
    "soilstress",
    "resume-api",
]


def upgrade() -> None:
    bind = op.get_bind()
    session = Session(bind=bind)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # table_obj=Skill.__table__ # type: ignore
    # table_obj.create(bind=op.get_bind())
    # create_db_and_tables()
    skills_dict = add_skills(session)
    project_categories_dict = add_project_categories(session)
    add_languages(session)
    profile = add_profile(session)
    add_tech_profile(session)
    add_education(session, profile)
    company_type_dict = add_company_type(session)
    companies_dict = add_companies(session, company_type_dict)
    professional_experiences_list = add_professional_experiences(
        session, companies_dict
    )

    projects_dict: dict[project_keys, Project] = {
        "mobile-app-combustibles": Project(
            key="mobile-app-combustibles",
            categories=[
                project_categories_dict["App"],
                project_categories_dict["Projects"],
            ],
            professional_experience=professional_experiences_list["cice_experience"],
            project="Mobile app: Fuel Dispatch",
            start_date=date(2012, 1, 1),
            end_date=date(2012, 9, 1),
            shortDescription="A mobile application for Android devices, built using the Adobe AIR platform, designed to register fuel dispatches.",
            fullDescription="A mobile application for Android devices, built using the Adobe AIR platform, designed to register fuel dispatches.",
            link="/img/portfolio/app1.jpg",
            projectLink="#",
            cover="./projects/combustibles/cover.png",
            project_company_type=company_type_dict["international_trade_company_type"],
            skills=[
                skills_dict["Adobe AIR"],
                skills_dict["Adobe Flex"],
                skills_dict["ActionScript 3.0"],
                skills_dict["Adobe Photoshop"],
                skills_dict["Adobe Illustrator"],
                skills_dict["Adobe InDesign"],
                skills_dict["Technical Documentation"],
                skills_dict["UML"],
                skills_dict["CSS/SCSS"],
                skills_dict["UI/UX"],
            ],
            responsibilities=[
                Responsibility(
                    description="Led the collection and analysis of functional and non-functional requirements to ensure a comprehensive understanding of project objectives."
                ),
                Responsibility(
                    description="Managed the strategic planning and project deliverable roadmap, ensuring timely completion and alignment with business goals."
                ),
                Responsibility(
                    description="Collaborated closely with team leadership on the planning and execution of backend API integrations, ensuring seamless system communication."
                ),
                Responsibility(
                    description="Spearheaded the design of a new UI/UX from scratch, creating a modern and intuitive user experience."
                ),
                Responsibility(
                    description="Developed mobile applications using Adobe Flex/Adobe Air, consuming SOAP services to integrate with Java-based backend APIs and enhance functionality."
                ),
                Responsibility(
                    description="Conducted user training sessions on the new application, driving user adoption and addressing technical inquiries to ensure a smooth transition."
                ),
                Responsibility(
                    description="Authored and maintained detailed technical documentation, improving cross-functional team collaboration and project clarity."
                ),
                Responsibility(
                    description="Created comprehensive user manuals, optimizing the end-user experience and significantly reducing support requests."
                ),
            ],
        ),
        "mobile-app-tarjado": Project(
            key="mobile-app-tarjado",
            categories=[
                project_categories_dict["App"],
                project_categories_dict["Projects"],
            ],
            professional_experience=professional_experiences_list["cice_experience"],
            project="Vessel Tallying Mobile Application",
            start_date=date(2012, 9, 1),
            end_date=date(2013, 4, 1),
            shortDescription="The Vessel Tallying Application was designed to replace the old Tallying system used at GRUPO CICE.",
            fullDescription="The Vessel Tallying Application was designed to replace the old Tallying system used at GRUPO CICE.",
            link="/portfolio/app1.jpg",
            projectLink="#",
            cover="./projects/tarjado/cover.png",
            project_company_type=company_type_dict["international_trade_company_type"],
            skills=[
                skills_dict["Adobe AIR"],
                skills_dict["Adobe Flex"],
                skills_dict["ActionScript 3.0"],
                skills_dict["Robotlegs"],
                skills_dict["Design Patterns"],
                skills_dict["Adobe Photoshop"],
                skills_dict["Adobe Illustrator"],
                skills_dict["Adobe InDesign"],
                skills_dict["Technical Documentation"],
                skills_dict["UML"],
                skills_dict["CSS/SCSS"],
                skills_dict["UI/UX"],
            ],
            responsibilities=[
                Responsibility(
                    description="Led the collection and analysis of functional and non-functional requirements to ensure a comprehensive understanding of project objectives."
                ),
                Responsibility(
                    description="Managed the strategic planning and project deliverable roadmap, ensuring timely completion and alignment with business goals."
                ),
                Responsibility(
                    description="Collaborated closely with team leadership on the planning and execution of backend API integrations, ensuring seamless system communication."
                ),
                Responsibility(
                    description="Spearheaded the design of a new UI/UX from scratch, creating a modern and intuitive user experience."
                ),
                Responsibility(
                    description="Developed mobile applications using Adobe Flex/Adobe Air, consuming SOAP services to integrate with Java-based backend APIs and enhance functionality."
                ),
                Responsibility(
                    description="Conducted user training sessions on the new application, driving user adoption and addressing technical inquiries to ensure a smooth transition."
                ),
                Responsibility(
                    description="Authored and maintained detailed technical documentation, improving cross-functional team collaboration and project clarity."
                ),
                Responsibility(
                    description="Created comprehensive user manuals, optimizing the end-user experience and significantly reducing support requests."
                ),
            ],
        ),
        "mobile-app-resumen-op": Project(
            key="mobile-app-resumen-op",
            professional_experience=professional_experiences_list["cice_experience"],
            categories=[
                project_categories_dict["App"],
                project_categories_dict["Projects"],
            ],
            project="Operations Summary Mobile Application",
            start_date=date(2011, 9, 1),
            end_date=date(2012, 4, 1),
            shortDescription="The Vessel Tallying Application was designed to replace the old Tallying system used at GRUPO CICE.",
            fullDescription="The Vessel Tallying Application was designed to replace the old Tallying system used at GRUPO CICE.",
            link="/portfolio/app1.jpg",
            projectLink="#",
            cover="./projects/tarjado/cover.png",
            project_company_type=company_type_dict["international_trade_company_type"],
            skills=[
                skills_dict["Java"],
                skills_dict["Android Development"],
                skills_dict["Adobe Photoshop"],
                skills_dict["Adobe Illustrator"],
                skills_dict["Adobe InDesign"],
                skills_dict["Technical Documentation"],
                skills_dict["UML"],
                skills_dict["CSS/SCSS"],
                skills_dict["UI/UX"],
            ],
            responsibilities=[
                Responsibility(
                    description="Led the collection and analysis of functional and non-functional requirements to ensure a comprehensive understanding of project objectives."
                ),
                Responsibility(
                    description="Managed the strategic planning and project deliverable roadmap, ensuring timely completion and alignment with business goals."
                ),
                Responsibility(
                    description="Collaborated closely with team leadership on the planning and execution of backend API integrations, ensuring seamless system communication."
                ),
                Responsibility(
                    description="Spearheaded the design of a new UI/UX from scratch, creating a modern and intuitive user experience."
                ),
                Responsibility(
                    description="Developed mobile applications using Android SDK, consuming REST services to integrate with Java-based backend APIs and enhance functionality."
                ),
                Responsibility(
                    description="Conducted user training sessions on the new application, driving user adoption and addressing technical inquiries to ensure a smooth transition."
                ),
                Responsibility(
                    description="Authored and maintained detailed technical documentation, improving cross-functional team collaboration and project clarity."
                ),
                Responsibility(
                    description="Created comprehensive user manuals, optimizing the end-user experience and significantly reducing support requests."
                ),
            ],
        ),
        "app-rec-aduanero": Project(
            key="app-rec-aduanero",
            professional_experience=professional_experiences_list["cice_experience"],
            categories=[
                project_categories_dict["App"],
                project_categories_dict["Projects"],
            ],
            project="Customs Recognition Tallying Application",
            start_date=date(2012, 9, 1),
            end_date=date(2013, 4, 1),
            shortDescription="The Customs Recognition Tallying Application aims to record customs recognition service requests and register the execution of these services.",
            fullDescription="The Customs Recognition Tallying Application aims to record customs recognition service requests and register the execution of these services.",
            link="/portfolio/app1.jpg",
            projectLink="#",
            cover="./projects/tarjado/cover.png",
            project_company_type=company_type_dict["international_trade_company_type"],
            skills=[
                skills_dict["Java"],
                skills_dict["Android Development"],
                skills_dict["Adobe Photoshop"],
                skills_dict["Adobe Illustrator"],
                skills_dict["Adobe InDesign"],
                skills_dict["Technical Documentation"],
                skills_dict["UML"],
                skills_dict["CSS/SCSS"],
                skills_dict["UI/UX"],
                skills_dict["Scrum"],
            ],
            responsibilities=[
                Responsibility(
                    description="Led the collection and analysis of functional and non-functional requirements to ensure a comprehensive understanding of project objectives."
                ),
                Responsibility(
                    description="Managed the strategic planning and project deliverable roadmap, ensuring timely completion and alignment with business goals."
                ),
                Responsibility(
                    description="Collaborated closely with team leadership on the planning and execution of backend API developing and integration with existing Oracle store procedures, ensuring seamless system communication."
                ),
                Responsibility(
                    description="Spearheaded the design of a new UI/UX from scratch, creating a modern and intuitive user experience."
                ),
                Responsibility(
                    description="Developed mobile applications using Android SDK, consuming REST services to integrate with Java-based backend APIs and enhance functionality."
                ),
                Responsibility(
                    description="Conducted user training sessions on the new application, driving user adoption and addressing technical inquiries to ensure a smooth transition."
                ),
                Responsibility(
                    description="Authored and maintained detailed technical documentation, improving cross-functional team collaboration and project clarity."
                ),
                Responsibility(
                    description="Created comprehensive user manuals, optimizing the end-user experience and significantly reducing support requests."
                ),
            ],
        ),
        "app-doc-approval": Project(
            key="app-doc-approval",
            professional_experience=professional_experiences_list["cice_experience"],
            categories=[
                project_categories_dict["App"],
                project_categories_dict["Projects"],
            ],
            project="Document Approval Mobile App",
            start_date=date(2013, 9, 1),
            end_date=date(2014, 9, 1),
            shortDescription="The Document Approval Mobile App was designed to facilitate document approval from mobile devices.",
            fullDescription="The Document Approval Mobile App was designed to facilitate document approval from mobile devices.",
            link="/portfolio/app1.jpg",
            projectLink="#",
            cover="./projects/tarjado/cover.png",
            project_company_type=company_type_dict["international_trade_company_type"],
            skills=[
                skills_dict["Android Development"],
                skills_dict["Ionic"],
                skills_dict["Angular"],
                skills_dict["Javascript"],
                skills_dict["PhoneGap"],
                skills_dict["Material Design"],
                skills_dict["Adobe Photoshop"],
                skills_dict["Adobe Illustrator"],
                skills_dict["Adobe InDesign"],
                skills_dict["Technical Documentation"],
                skills_dict["UML"],
                skills_dict["CSS/SCSS"],
                skills_dict["UI/UX"],
                skills_dict["Java"],
                skills_dict["Scrum"],
            ],
            responsibilities=[
                Responsibility(
                    description="Led the collection and analysis of functional and non-functional requirements to ensure a comprehensive understanding of project objectives."
                ),
                Responsibility(
                    description="Managed the strategic planning and project deliverable roadmap, ensuring timely completion and alignment with business goals."
                ),
                Responsibility(
                    description="Collaborated closely with team leadership on the planning and execution of backend API developing and integration with existing Oracle store procedures, ensuring seamless system communication."
                ),
                Responsibility(
                    description="Spearheaded the design of a new UI/UX from scratch, creating a modern and intuitive user experience."
                ),
                Responsibility(
                    description="Developed mobile applications using Ionic framework, consuming REST services to integrate with Java-based backend APIs and enhance functionality."
                ),
                Responsibility(
                    description="Authored and maintained detailed technical documentation, improving cross-functional team collaboration and project clarity."
                ),
                Responsibility(
                    description="Created comprehensive user manuals, optimizing the end-user experience and significantly reducing support requests."
                ),
                Responsibility(
                    description="Managed and executed the complete deployment of the application to the Google Play Store and Apple App Store, ensuring compliance with all publishing guidelines."
                ),
            ],
        ),
        "app-contenedores": Project(
            key="app-contenedores",
            professional_experience=professional_experiences_list["cice_experience"],
            categories=[
                project_categories_dict["App"],
                project_categories_dict["Projects"],
            ],
            project="Container Approval Web App",
            start_date=date(2014, 9, 1),
            end_date=date(2015, 4, 1),
            shortDescription="The Container Approval Web App was designed to facilitate container approval from mobile devices.",
            fullDescription="The Container Approval Web App was designed to facilitate container approval from mobile devices.",
            link="/portfolio/app1.jpg",
            projectLink="#",
            cover="./projects/tarjado/cover.png",
            project_company_type=company_type_dict["international_trade_company_type"],
            skills=[
                skills_dict["Android Development"],
                skills_dict["Ionic"],
                skills_dict["Angular"],
                skills_dict["Javascript"],
                skills_dict["Material Design"],
                skills_dict["Cordova"],
                skills_dict["PhoneGap"],
                skills_dict["Adobe Photoshop"],
                skills_dict["Adobe Illustrator"],
                skills_dict["Adobe InDesign"],
                skills_dict["Technical Documentation"],
                skills_dict["UML"],
                skills_dict["CSS/SCSS"],
                skills_dict["UI/UX"],
                skills_dict["Java"],
                skills_dict["Scrum"],
            ],
            responsibilities=[
                Responsibility(
                    description="Led the collection and analysis of functional and non-functional requirements to ensure a comprehensive understanding of project objectives."
                ),
                Responsibility(
                    description="Managed the strategic planning and project deliverable roadmap, ensuring timely completion and alignment with business goals."
                ),
                Responsibility(
                    description="Collaborated closely with team leadership on the planning and execution of backend API developing and integration with existing Oracle store procedures, ensuring seamless system communication."
                ),
                Responsibility(
                    description="Spearheaded the design of a new UI/UX from scratch, creating a modern and intuitive user experience."
                ),
                Responsibility(
                    description="Developed mobile applications using Ionic framework, consuming REST services to integrate with Java-based backend APIs and enhance functionality."
                ),
                Responsibility(
                    description="Authored and maintained detailed technical documentation, improving cross-functional team collaboration and project clarity."
                ),
                Responsibility(
                    description="Created comprehensive user manuals, optimizing the end-user experience and significantly reducing support requests."
                ),
            ],
        ),
        "app-live-in-tour": Project(
            key="app-live-in-tour",
            professional_experience=professional_experiences_list["ehecatl_experience"],
            categories=[
                project_categories_dict["App"],
                project_categories_dict["Projects"],
            ],
            project="Live In Tour (Android)",
            start_date=date(2015, 7, 1),
            end_date=date(2015, 10, 1),
            shortDescription="The LiveIntour application utilizes the Android SDK and Metaio SDK to achieve Augmented Reality and geolocation functionality on mobile devices.",
            fullDescription="The LiveIntour application utilizes the Android SDK and Metaio SDK to achieve Augmented Reality and geolocation functionality on mobile devices.",
            link="/portfolio/app1.jpg",
            projectLink="#",
            cover="./projects/tarjado/cover.png",
            project_company_type=company_type_dict["augmented_reality_marketing"],
            skills=[
                skills_dict["Android Development"],
                skills_dict["Material Design"],
                skills_dict["Metaio framework"],
                skills_dict["Augmented Reality"],
                skills_dict["Technical Documentation"],
                skills_dict["Java"],
            ],
            responsibilities=[
                Responsibility(
                    description="Led the collection and analysis of functional and non-functional requirements to ensure a comprehensive understanding of project objectives."
                ),
                Responsibility(
                    description="Managed the strategic planning and project deliverable roadmap, ensuring timely completion and alignment with business goals."
                ),
                Responsibility(
                    description="Integrated the Metaio framework to implement high-performance augmented reality features, creating interactive and immersive user experiences."
                ),
                Responsibility(
                    description="Authored and maintained detailed technical documentation, improving cross-functional team collaboration and project clarity."
                ),
            ],
        ),
        "app-echocalc": Project(
            key="app-echocalc",
            professional_experience=professional_experiences_list["ehecatl_experience"],
            categories=[
                project_categories_dict["App"],
                project_categories_dict["Projects"],
            ],
            project="Live In Tour (Android)",
            start_date=date(2015, 10, 1),
            end_date=date(2015, 11, 1),
            shortDescription="Implementing a calculator application for various health operations. Utilizing a code base implemented in HTML.",
            fullDescription="Implementing a calculator application for various health operations. Utilizing a code base implemented in HTML.",
            link="/portfolio/app1.jpg",
            projectLink="#",
            cover="./projects/tarjado/cover.png",
            project_company_type=company_type_dict["healtcare_company_type"],
            skills=[
                skills_dict["Android Development"],
                skills_dict["HTML"],
                skills_dict["CSS/SCSS"],
                skills_dict["Javascript"],
                skills_dict["Technical Documentation"],
                skills_dict["Java"],
            ],
            responsibilities=[
                Responsibility(
                    description="Led the collection and analysis of functional and non-functional requirements to ensure a comprehensive understanding of project objectives."
                ),
                Responsibility(
                    description="Managed the strategic planning and project deliverable roadmap, ensuring timely completion and alignment with business goals."
                ),
                Responsibility(
                    description="Integrated the Metaio framework to implement high-performance augmented reality features, creating interactive and immersive user experiences."
                ),
                Responsibility(
                    description="Authored and maintained detailed technical documentation, improving cross-functional team collaboration and project clarity."
                ),
            ],
        ),
        "app-hectorizate": Project(
            key="app-hectorizate",
            professional_experience=professional_experiences_list["ehecatl_experience"],
            categories=[
                project_categories_dict["App"],
                project_categories_dict["Projects"],
            ],
            project="Hectorizate (Android)",
            start_date=date(2015, 11, 1),
            end_date=date(2015, 12, 1),
            shortDescription="Application with Augmented Reality for public figure.",
            fullDescription="Application with Augmented Reality for public figure.",
            link="/portfolio/app1.jpg",
            projectLink="#",
            cover="./projects/tarjado/cover.png",
            project_company_type=company_type_dict["augmented_reality_marketing"],
            skills=[
                skills_dict["Android Development"],
                skills_dict["HTML"],
                skills_dict["CSS/SCSS"],
                skills_dict["Technical Documentation"],
                skills_dict["Java"],
                skills_dict["Adobe Photoshop"],
                skills_dict["Adobe Illustrator"],
            ],
            responsibilities=[
                Responsibility(
                    description="Led the collection and analysis of functional and non-functional requirements to ensure a comprehensive understanding of project objectives."
                ),
                Responsibility(
                    description="Managed the strategic planning and project deliverable roadmap, ensuring timely completion and alignment with business goals."
                ),
                Responsibility(
                    description="Integrated the Metaio framework to implement high-performance augmented reality features, creating interactive and immersive user experiences."
                ),
                Responsibility(
                    description="Authored and maintained detailed technical documentation, improving cross-functional team collaboration and project clarity."
                ),
                Responsibility(
                    description="Optimized and adapted assets for responsive design, ensuring visual integrity across various screen sizes and resolutions."
                ),
            ],
        ),
        "web-dictamen": Project(
            key="web-dictamen",
            professional_experience=professional_experiences_list["ehecatl_experience"],
            categories=[
                project_categories_dict["App"],
                project_categories_dict["Projects"],
            ],
            project="El Dictamen Portal (Web)",
            start_date=date(2016, 1, 1),
            end_date=date(2016, 4, 1),
            shortDescription="Redesign of the El Dictamen website's style.",
            fullDescription="Redesign of the El Dictamen website's style.",
            link="/portfolio/app1.jpg",
            projectLink="#",
            cover="./projects/tarjado/cover.png",
            project_company_type=company_type_dict["media_&_communications"],
            skills=[
                skills_dict["Android Development"],
                skills_dict["HTML"],
                skills_dict["CSS/SCSS"],
                skills_dict["Javascript"],
                skills_dict["Technical Documentation"],
                skills_dict["Wordpress"],
                skills_dict["PHP"],
                skills_dict["Adobe Photoshop"],
                skills_dict["Adobe Illustrator"],
            ],
            responsibilities=[
                Responsibility(
                    description="Led the collection and analysis of functional and non-functional requirements to ensure a comprehensive understanding of project objectives."
                ),
                Responsibility(
                    description="Managed the strategic planning and project deliverable roadmap, ensuring timely completion and alignment with business goals."
                ),
                Responsibility(
                    description="Integrated the Metaio framework to implement high-performance augmented reality features, creating interactive and immersive user experiences."
                ),
                Responsibility(
                    description="Optimized and adapted assets for responsive design, ensuring visual integrity across various screen sizes and resolutions."
                ),
            ],
        ),
        "pizzap": Project(
            key="pizzap",
            professional_experience=professional_experiences_list["pizzapp_experience"],
            categories=[
                project_categories_dict["App"],
                project_categories_dict["Projects"],
                project_categories_dict["Web"],
            ],
            project="Pizzap web and mobile",
            start_date=date(2016, 1, 1),
            end_date=date(2016, 4, 1),
            shortDescription="Design and development of mobile and web portal for pizzapp",
            fullDescription="Design and development of mobile and web portal for pizzapp",
            link="/portfolio/app1.jpg",
            projectLink="#",
            cover="./projects/tarjado/cover.png",
            project_company_type=company_type_dict["media_&_communications"],
            skills=[
                skills_dict["Ionic"],
                skills_dict["Angular"],
                skills_dict["HTML"],
                skills_dict["CSS/SCSS"],
                skills_dict["Typescript"],
                skills_dict["Git"],
                skills_dict["Yeoman"],
                skills_dict["Firebase"],
                skills_dict["Adobe Photoshop"],
                skills_dict["Adobe Illustrator"],
                skills_dict["Technical Documentation"],
                skills_dict["Scrum"],
            ],
            responsibilities=[
                Responsibility(
                    description="Led the collection and analysis of functional and non-functional requirements to ensure a comprehensive understanding of project objectives."
                ),
                Responsibility(
                    description="Managed the strategic planning and project deliverable roadmap, ensuring timely completion and alignment with business goals."
                ),
                Responsibility(
                    description="Integrated the Metaio framework to implement high-performance augmented reality features, creating interactive and immersive user experiences."
                ),
                Responsibility(
                    description="Optimized and adapted assets for responsive design, ensuring visual integrity across various screen sizes and resolutions."
                ),
                Responsibility(
                    description="Created comprehensive user manuals, optimizing the end-user experience and significantly reducing support requests."
                ),
            ],
        ),
        "cesisccam": Project(
            key="cesisccam",
            professional_experience=professional_experiences_list[
                "inidetam_experience"
            ],
            categories=[
                project_categories_dict["Projects"],
            ],
            project="CESISCCAM",
            start_date=date(2016, 1, 1),
            end_date=date(2018, 4, 1),
            shortDescription="A set of simulation systems and support systems that allow naval personnel to train in two main areas: Operation Training and Maintenance Training, for the SEMAR Command and Control systems.",
            fullDescription="A set of simulation systems and support systems that allow naval personnel to train in two main areas: Operation Training and Maintenance Training, for the SEMAR Command and Control systems. (Source: https://www.semar.gob.mx/INIDETAM/proyectos.html#carousel-cesisccam) ",
            link="/portfolio/app1.jpg",
            projectLink="#",
            cover="./projects/tarjado/cover.png",
            project_company_type=company_type_dict["military_company_type"],
            skills=[
                skills_dict["Node.js"],
                skills_dict["Angular"],
                skills_dict["HTML"],
                skills_dict["CSS/SCSS"],
                skills_dict["Typescript"],
                skills_dict["Javascript"],
                skills_dict["Git"],
                skills_dict["Socket.io"],
                skills_dict["world_wind"],
                skills_dict["GIS"],
                skills_dict["Scrum"],
                skills_dict["event_driven_architecture"],
                skills_dict["Redux"],
                skills_dict["Design Patterns"],
                skills_dict["PostgreSQL"],
                skills_dict["MongoDB"],
                skills_dict["Express.js"],
                skills_dict["Kanban"],
                skills_dict["Pm2"],
            ],
            responsibilities=[
                Responsibility(
                    description="Designed and implemented from scratch the whole environment and motion Kinematic Module which basically was the core module for all the simulation with Nodejs. "
                ),
                Responsibility(
                    description="Developed and maintained web applications using Angular and Node.js \nCommunication Module:  A chat application implemented with angular and socket IO \nViewer Module:  A geospatial viewer implemented with WorldWind for visualization of the information sent by the core Kinematic Module. \nControls Module:   A control module for unit being simulated, (Aircraft, Boat/Ship or Terrestrial unit) "
                ),
                Responsibility(description="Co-leaded the Software development team "),
                Responsibility(
                    description="Collaborated with cross-functional teams to define, design, and ship new feature "
                ),
                Responsibility(
                    description="Participated in code reviews and contributed to team knowledge sharing"
                ),
                Responsibility(
                    description="Mentored the development team in agile and scrum methodologies, fostering a culture of continuous improvement and collaboration "
                ),
                Responsibility(
                    description="Mentored junior developers and interns and guided them in best practices "
                ),
                Responsibility(
                    description="Successfully present demos to project reviewers (SEMAR and Conacyt). "
                ),
                Responsibility(
                    description="Wrote Technical documentation for the developed modules  "
                ),
            ],
        ),
        "cbt": Project(
            key="cbt",
            professional_experience=professional_experiences_list[
                "tiempo_dev_experience"
            ],
            categories=[
                project_categories_dict["Projects"],
                project_categories_dict["Backend"],
            ],
            project="Cbt Nuggets (Web)",
            start_date=date(2018, 1, 1),
            end_date=date(2019, 12, 1),
            shortDescription="Online IT training platform offering a vast library of concise and engaging video courses led by expert instructors. It focuses on practical skills and certifications across various IT domains.",
            fullDescription="Online IT training platform offering a vast library of concise and engaging video courses led by expert instructors. It focuses on practical skills and certifications across various IT domains.",
            link="/portfolio/app1.jpg",
            projectLink="#",
            cover="./projects/tarjado/cover.png",
            project_company_type=company_type_dict["education_e_learning_company_type"],
            skills=[
                skills_dict["Node.js"],
                skills_dict["Javascript"],
                skills_dict["Typescript"],
                skills_dict["Git"],
                skills_dict["AWS"],
                skills_dict["GraphQL"],
                skills_dict["DynamoDB"],
                skills_dict["Scrum"],
                skills_dict["Microservices"],
                skills_dict["Design Patterns"],
                skills_dict["REST Services"],
            ],
            responsibilities=[
                Responsibility(
                    description="Partnered with cross-functional teams to define, design, and launch new product features, ensuring alignment with project goals."
                ),
                Responsibility(
                    description="Engineered and implemented robust backend endpoints to support critical application functionalities"
                ),
                Responsibility(
                    description="Authored and executed unit tests to ensure code quality and maintain high application reliability."
                ),
                Responsibility(
                    description="Actively participated in code reviews, providing constructive feedback to maintain code quality standards and mentor junior developers"
                ),
                Responsibility(
                    description="Contributed to technical discussions and architectural planning, helping shape key product decisions and solutions."
                ),
                Responsibility(
                    description="Created and maintained comprehensive technical documentation, improving knowledge sharing and onboarding for new team members"
                ),
                Responsibility(
                    description="Actively participated in Scrum ceremonies, providing clear progress updates and contributing to sprint planning and retrospectives to improve team efficiency"
                ),
            ],
        ),
        "amps": Project(
            key="amps",
            professional_experience=professional_experiences_list[
                "tiempo_dev_experience"
            ],
            categories=[
                project_categories_dict["Projects"],
                project_categories_dict["Fullstack"],
                project_categories_dict["Web"],
            ],
            project="Amp: Advanced Medical Pricing",
            start_date=date(2020, 1, 1),
            end_date=date(2022, 1, 1),
            shortDescription="Healthcare cost reduction for self-funded organizations.",
            fullDescription="Healthcare cost reduction for self-funded organizations.",
            link="/portfolio/app1.jpg",
            projectLink="#",
            cover="./projects/tarjado/cover.png",
            project_company_type=company_type_dict["healtcare_company_type"],
            skills=[
                skills_dict["Node.js"],
                skills_dict["NestJs"],
                skills_dict["React"],
                skills_dict["Javascript"],
                skills_dict["Typescript"],
                skills_dict["Git"],
                skills_dict["AWS"],
                skills_dict["Scrum"],
                skills_dict["Microservices"],
                skills_dict["Design Patterns"],
                skills_dict["REST Services"],
                skills_dict["TypeOrm"],
                skills_dict["Postman"],
            ],
            responsibilities=[
                Responsibility(
                    description="Partnered with cross-functional teams to define and design new features, guiding them from concept to production launch."
                ),
                Responsibility(
                    description="Engineered and implemented new backend endpoints to support key application functionalities and enhance system performance."
                ),
                Responsibility(
                    description="Supporting the efforts for introducing RabittMQ to follow the recommended Nestjs way of Microservices communication"
                ),
                Responsibility(
                    description="Developed modular and reusable React components to build a modern and scalable user interface."
                ),
                Responsibility(
                    description="Assisted in the implementation of Storybook to create a centralized catalog of reusable React components, improving development efficiency and consistency."
                ),
                Responsibility(
                    description="Contributed to the backend testing efforts during the project's ramp-down phase, ensuring code quality and a smooth transition to maintenance."
                ),
            ],
        ),
        "nielsen": Project(
            key="nielsen",
            professional_experience=professional_experiences_list[
                "three_pillar_gobal_experience"
            ],
            categories=[
                project_categories_dict["Projects"],
                project_categories_dict["Frontend"],
                project_categories_dict["Web"],
            ],
            project="NielsenIQ",
            start_date=date(2022, 1, 1),
            end_date=date(2023, 1, 1),
            shortDescription="Platform for providing market research, data  analytics and insights to retailers and consumer packaged goods.",
            fullDescription="Platform for providing market research, data  analytics and insights to retailers and consumer packaged goods.",
            link="/portfolio/app1.jpg",
            projectLink="#",
            cover="./projects/tarjado/cover.png",
            project_company_type=company_type_dict[
                "business_intelligence_company_type"
            ],
            skills=[
                skills_dict["Node.js"],
                skills_dict["Typescript"],
                skills_dict["Git"],
                skills_dict["Scrum"],
                skills_dict["Design Patterns"],
                skills_dict["Microservices"],
                skills_dict["REST Services"],
                skills_dict["Clean Architecture"],
                skills_dict["SOLID_principles"],
                skills_dict["Redux"],
                skills_dict["RxJS Observables"],
                skills_dict["Storybook"],
                skills_dict["Figma"],
            ],
            responsibilities=[
                Responsibility(
                    description="Collaborated with cross-functional teams to define, design, and ship new features"
                ),
                Responsibility(
                    description="Mentoring team members on advanced Angular topics like the hierarchy of the DI Injection tokens, and SOLID principles"
                ),
                Responsibility(
                    description="Decoupled a variety of observable pipelines which allowed the reusability and implementation of new features"
                ),
                Responsibility(
                    description="Leaded along with the technical lead the initiative of creating a system design based on storybook for reusable components. "
                ),
            ],
        ),
        "centene": Project(
            key="centene",
            professional_experience=professional_experiences_list[
                "three_pillar_gobal_experience"
            ],
            categories=[
                project_categories_dict["Projects"],
                project_categories_dict["Fullstack"],
                project_categories_dict["Web"],
            ],
            project="Centene",
            start_date=date(2023, 1, 1),
            end_date=date(2024, 1, 1),
            shortDescription="The Centene project involved developing a healthcare portal composed of two distinct applications.\nThe first application provided users with comprehensive account and coverage information, enabling them to access and download their credentials. (ReactJs) \nThe second application featured an affiliate search engine, allowing users to find eligible healthcare providers based on their contracted plan, coverage, and geolocation parameters. (NextJs) ",
            fullDescription="The Centene project involved developing a healthcare portal composed of two distinct applications.\nThe first application provided users with comprehensive account and coverage information, enabling them to access and download their credentials. (ReactJs) \nThe second application featured an affiliate search engine, allowing users to find eligible healthcare providers based on their contracted plan, coverage, and geolocation parameters. (NextJs) ",
            link="/portfolio/app1.jpg",
            projectLink="#",
            cover="./projects/tarjado/cover.png",
            project_company_type=company_type_dict["medical_insurance_company_type"],
            skills=[
                skills_dict["Node.js"],
                skills_dict["Typescript"],
                skills_dict["Docker"],
                skills_dict["Git"],
                skills_dict["Scrum"],
                skills_dict["Design Patterns"],
                skills_dict["Microservices"],
                skills_dict["REST Services"],
                skills_dict["Clean Architecture"],
                skills_dict["SOLID_principles"],
                skills_dict["Redux"],
                skills_dict["React"],
                skills_dict["Next.js"],
                skills_dict["Storybook"],
                skills_dict["Technical Documentation"],
                skills_dict["Technical Support"],
                skills_dict["Prisma ORM"],
            ],
            responsibilities=[
                Responsibility(
                    description="Collaborated with cross-functional teams to define, design, and ship new features"
                ),
                Responsibility(
                    description="Mentoring team members on advanced Angular topics like the hierarchy of the DI Injection tokens, and SOLID principles"
                ),
                Responsibility(
                    description="Decoupled a variety of observable pipelines which allowed the reusability and implementation of new features"
                ),
                Responsibility(
                    description="Leaded along with the technical lead the initiative of creating a system design based on storybook for reusable components. "
                ),
            ],
        ),
        "soilstress": Project(
            key="soilstress",
            professional_experience=professional_experiences_list[
                "independent_experience"
            ],
            categories=[
                project_categories_dict["Projects"],
                project_categories_dict["Fullstack"],
                project_categories_dict["App"],
            ],
            project="Soil Stress Calculator",
            start_date=date(2025, 1, 1),
            end_date=date(2024, 1, 1),
            shortDescription="Initially, I was approached by researchers from the UNAM Faculty of Engineering to provide a Python Object-Oriented Programming course. This training was crucial for a research paper they were developing for an upcoming convention. Following the course, I was contracted to develop the visualization module and implement the algorithms for calculating vertical stress in soils, directly contributing to their research project.",
            fullDescription="Initially, I was approached by researchers from the UNAM Faculty of Engineering to provide a Python Object-Oriented Programming course. This training was crucial for a research paper they were developing for an upcoming convention. Following the course, I was contracted to develop the visualization module and implement the algorithms for calculating vertical stress in soils, directly contributing to their research project.",
            link="/portfolio/app1.jpg",
            projectLink="#",
            cover="./projects/tarjado/cover.png",
            project_company_type=company_type_dict["medical_insurance_company_type"],
            skills=[
                skills_dict["OOP"],
                skills_dict["Git"],
                skills_dict["Design Patterns"],
                skills_dict["Clean Architecture"],
                skills_dict["SOLID_principles"],
                skills_dict["Python"], 
                skills_dict["PySide6"], 
                skills_dict["numpy"], 
                skills_dict["matplotlib"], 
                skills_dict["pandas"],
                skills_dict["dask"],
                skills_dict["FastAPI"]
                
            ],
            responsibilities=[
                Responsibility(description="Developed the curriculum and delivered classes, enabling students to learn the fundamentals of Python programming and Object-Oriented Programming (OOP). "),
                Responsibility(description="Developed a module/library ready for PyPI publication, featuring a catalog of methods for calculating vertical stress in soils. "),
                Responsibility(description="Designed the graphical user interface (GUI) for the system, facilitating data loading and calculation visualization. "),
                Responsibility(description="Optimized algorithms, reducing the computation time of the base implementation by 40%."),
                Responsibility(description="Developed an API for executing the algorithms from a server (ultimately implemented within a desktop application)."),
            ],
        ),
        "goKarts": Project(
            key="goKarts",
            professional_experience=professional_experiences_list[
                "independent_experience"
            ],
            categories=[
                project_categories_dict["Fullstack"],
                project_categories_dict["App"],
            ],
            project="goKarts race leaderboard",
            start_date=date(2025, 1, 1),
            end_date=date(2024, 1, 1),
            shortDescription="The Go-Karts Race Leaderboard project was conducted in two main phases. The initial development took place from 2020 to 2021 but was paused due to the pandemic. Work on the project resumed and between 2024 and 2025. \nThis project is a leaderboard and informational dashboard for a go-kart racing league. Originally, it was conceived as a desktop application to replace the spreadsheet used to track race results. It was later redesigned and developed as a web application, giving drivers direct access to their personal statistics and scores. ",
            fullDescription="The Go-Karts Race Leaderboard project was conducted in two main phases. The initial development took place from 2020 to 2021 but was paused due to the pandemic. Work on the project resumed and between 2024 and 2025. \nThis project is a leaderboard and informational dashboard for a go-kart racing league. Originally, it was conceived as a desktop application to replace the spreadsheet used to track race results. It was later redesigned and developed as a web application, giving drivers direct access to their personal statistics and scores. ",
            link="/portfolio/app1.jpg",
            projectLink="#",
            cover="./projects/tarjado/cover.png",
            project_company_type=company_type_dict["sports"],
            skills=[
                skills_dict["OOP"],
                skills_dict["Git"],
                skills_dict["Design Patterns"],
                skills_dict["Clean Architecture"],
                skills_dict["SOLID_principles"],
                skills_dict["Python"], 
                skills_dict["PySide6"], 
                skills_dict["React"], 
                skills_dict["alembic"], 
            ],
            responsibilities=[
                Responsibility(description="Requirements gathering and initial project conceptualization."),
                Responsibility(description="Environment setup and core technology stack definition. "),
                Responsibility(description="User interface design for the desktop application. "),
                Responsibility(description="Database migrations created using Alembic. "),
                Responsibility(description="Minimum Viable Product (MVP) development. "),
                Responsibility(description="Code refactoring to align with a layered architecture, facilitating entity migration to a FastAPI-based API project. "),
                Responsibility(description="Frontend project definition using Vite + React.js. "),
            ],
        ),
        "resume-api": Project(
            key="resume-api",
            professional_experience=professional_experiences_list[
                "independent_experience"
            ],
            categories=[
                project_categories_dict["Fullstack"],
                project_categories_dict["App"],
            ],
            project="Resume API",
            start_date=date(2024, 1, 1),
            end_date=date(2025, 1, 1),
            shortDescription="Personal web portfolio and a backend API that intelligently automates resume generation",
            fullDescription="personal web portfolio and a backend API that intelligently automates resume generation. The system analyzes job descriptions and dynamically tailors the resume's content to highlight the most relevant skills and experience, optimizing job applications for specific roles. This project demonstrates my expertise in full-stack development, API integration, and creating efficient solutions that address a real-world problem.",
            link="/portfolio/app1.jpg",
            projectLink="#",
            cover="./projects/tarjado/cover.png",
            project_company_type=company_type_dict["sports"],
            skills=[
                skills_dict["OOP"],
                skills_dict["Git"],
                skills_dict["Design Patterns"],
                skills_dict["Clean Architecture"],
                skills_dict["SOLID_principles"],
                skills_dict["Domain Driven Design"], 
                skills_dict["Python"], 
                skills_dict["PySide6"], 
                skills_dict["React"], 
                skills_dict["Tailwind CSS"], 
                skills_dict["alembic"], 
                skills_dict["SQLModel"], 
                skills_dict["FastAPI"], 
                skills_dict["Render"], 
                skills_dict["Supabase"], 
                skills_dict["CI/CD"], 
                skills_dict["Github Actions"], 
                skills_dict["Github Pages"], 
            ],
            responsibilities=[
                Responsibility(description="Architected and developed a full-stack web application using Python, FastAPI, and React, following Clean Architecture and Domain-Driven Design principles to ensure a scalable and maintainable system."),
                Responsibility(description="Engineered a RESTful API to process job descriptions and dynamically tailor resume content, utilizing SQLModel for object-relational mapping and managing data with Supabase."),
                Responsibility(description="Implemented automated database migrations with Alembic, ensuring seamless schema updates and data integrity across development and production environments."),
                Responsibility(description="Built a responsive user interface with React that allows users to input data and generate personalized resumes, effectively consuming the custom-built FastAPI backend."),
                Responsibility(description="Designed and implemented a CI/CD pipeline using GitHub Actions to automate  deployment to Render."),
                Responsibility(description="Applied core programming principles such as OOP and SOLID throughout the codebase to deliver a robust, well-tested, and clean solution."),
            ],
        ),
    }

    session.add_all(list(projects_dict.values()))

    session.commit()


def add_professional_experiences(session, companies_dict):
    professional_experiences_dict: dict[
        professional_experiences_key, ProfessionalExperience
    ] = {
        "cice_experience": ProfessionalExperience(
            company=companies_dict["cice"],
            key="neus-team-grupo-cice",
            startDate=date(2011, 1, 1),
            endDate=date(2015, 1, 1),
            position="Software Services Provider/Fullstack Developer",
        ),
        "ehecatl_experience": ProfessionalExperience(
            company=companies_dict["ehecatl"],
            key="ehecatl-software-services",
            startDate=date(2015, 1, 1),
            endDate=date(2016, 1, 1),
            position="Frontend and Mobile Developer",
        ),
        "pizzapp_experience": ProfessionalExperience(
            company=companies_dict["pizzapp"],
            key="pizzap",
            startDate=date(2016, 1, 1),
            endDate=date(2016, 1, 1),
            position="Frontend and Mobile Developer",
        ),
        "inidetam_experience": ProfessionalExperience(
            company=companies_dict["inidetam"],
            key="inidetam",
            startDate=date(2016, 1, 1),
            endDate=date(2018, 1, 1),
            position="Software Engineer Fullstack",
        ),
        "tiempo_dev_experience": ProfessionalExperience(
            company=companies_dict["tiempo_development"],
            key="tiempo-development-software-engineer",
            startDate=date(2018, 1, 1),
            endDate=date(2020, 1, 1),
            position="Software Engineer III (Fullstack)",
        ),
        "three_pillar_gobal_experience": ProfessionalExperience(
            company=companies_dict["three_pillar_global"],
            key="3pg-senior-software-engineer",
            startDate=date(2020, 1, 1),
            endDate=date(2024, 1, 1),
            position="Senior Software Engineer",
        ),
        "independent_experience": ProfessionalExperience(
            company=companies_dict["independent"],
            key="idependent-1",
            startDate=date(2024, 1, 1),
            endDate=date(2025, 1, 1),
            position="Independent Software Engineer",
        ),
    }
    professional_experiences: list[ProfessionalExperience] = [
        pe for pe in professional_experiences_dict.values()
    ]
    session.add_all(professional_experiences)
    return professional_experiences_dict


def add_companies(session, company_type_dict):
    companies_dict: dict[str, Company] = {
        "cice": Company(
            company_type=company_type_dict["international_trade_company_type"],
            name="Grupo CICE",
        ),
        "ehecatl": Company(
            company_type=company_type_dict["software_consultant_company_type"],
            name="Ehecatl Software Services",
        ),
        "pizzapp": Company(company_type=company_type_dict["startup"], name="Pizzapp"),
        "inidetam": Company(
            company_type=company_type_dict["military_company_type"],
            name="Instituto de Investigación y Desarrollo Tecnológico de la Armada de México",
        ),
        "tiempo_development": Company(
            company_type=company_type_dict["software_consultant_company_type"],
            name="Tiempo Development",
        ),
        "three_pillar_global": Company(
            company_type=company_type_dict["software_consultant_company_type"],
            name="3Pillar Global",
        ),
        "independent": Company(
            company_type=company_type_dict["independent"],
            name="Independent Consultant/Freelance",
        ),
    }

    companies: list[Company] = list(companies_dict.values())

    session.add_all(companies)
    return companies_dict


def add_company_type(session):
    company_type_dic: dict[
        Literal[
            "healtcare_company_type",
            "medical_insurance_company_type",
            "education_e_learning_company_type",
            "business_intelligence_company_type",
            "military_company_type",
            "international_trade_company_type",
            "scientific_research_company_type",
            "software_consultant_company_type",
            "startup",
            "independent",
            "augmented_reality_marketing",
            "media_&_communications",
            "sports"
        ],
        CompanyType,
    ] = {
        "healtcare_company_type": CompanyType(name="Healthcare"),
        "medical_insurance_company_type": CompanyType(name="Medical Insurance"),
        "education_e_learning_company_type": CompanyType(name="Education/E-learning"),
        "business_intelligence_company_type": CompanyType(name="Business Intelligence"),
        "military_company_type": CompanyType(name="Military"),
        "international_trade_company_type": CompanyType(name="International Trade"),
        "scientific_research_company_type": CompanyType(name="Scientific Research"),
        "software_consultant_company_type": CompanyType(name="Software Consultant"),
        "startup": CompanyType(name="Startup"),
        "independent": CompanyType(name="Independent"),
        "augmented_reality_marketing": CompanyType(name="Augmented Reality Marketing"),
        "media_&_communications": CompanyType(name="Media & Communications"),
        "sports": CompanyType(name="Sports"),
    }

    company_type_list = list(company_type_dic.values())

    session.add_all(company_type_list)
    return company_type_dic


def add_education(session, profile):
    education = [
        Education(
            title="Bachelor's Degree in Computing Sciences",
            dateStart=date(2005, 1, 1),
            dateFinished=date(2009, 1, 1),
            institute="Instituto Tecnologico de Veracruz,Veracruz, Mexico",
            description="Bachelor's Degree in Computing Sciences. | Instituto Tecnologico de Veraacruz",
            user_id=profile.id,
        ),
        Education(
            title="Adobe Certified Expert on Flex 3 with AIR 3",
            dateStart=date(2010, 1, 1),
            dateFinished=date(2011, 1, 1),
            institute="Argot Training Center, Adobe Authorized Training Center",
            description="An Adobe Flex certification for developing Rich internet applications",
            user_id=profile.id,
        ),
        Education(
            title="Certified Scrum Master",
            dateStart=date(2014, 1, 1),
            dateFinished=date(2016, 1, 1),
            institute="Scrum Alliance",
            description="Scrum Master Certification obtained by the Scrum Alliance ",
            user_id=profile.id,
        ),
    ] 
    session.add_all(education)


def add_tech_profile(session):
    tech_profiles = [
        TechProfile(
            focus="Nodejs Fullstack Developer",
            description="I'm a versatile Full Stack Software Engineer with over 10 years of experience, specializing in building robust and \nscalable solutions. My expertise ranges from developing interactive frontends with React and Angular to implementing efficient APIs with Python (including FastAPI and Django REST Framework), Node.js, and Express.js. I also possess strong skills in SQL and NoSQL database management. \nThroughout my career, I've embraced diverse roles, including Scrum Master, Team Lead, Tester, Technical Documentation specialist, UX Designer, System Designer, and Mentor. This broad experience has not only sharpened my technical acumen but also provided me with a comprehensive understanding of the entire software development lifecycle.\n Recently, I've found my greatest impact and growth in roles as a technical second-in-command, where I thrive on supporting leadership and driving technical initiatives. I'm actively aspiring to advance into greater technical leadership responsibilities.\n I'm passionate about software architecture, system optimization, and am currently focused on learning and implementing Artificial Intelligence solutions. I'm particularly interested in the creation of multi-layered agents (MCP) and workflow automation with tools like n8n, aiming to integrate advanced AI capabilities into complex systems",
        )
    ]
    session.add_all(tech_profiles)


def add_profile(session):
    profile = Profile(
        id=UUID('85faeb1c591d4e95af363d87b92d3996'),
        name="Mario Alberto Rivera Dominguez",
        birthday=date(1986, 11, 10),
        city="San Pedro Tlaquepaque, Jalisco",
        phone="+52 229-148-6661",
        freelance="available",
        email="ace.mrivera@gmail.com",
        degree="Bachelor Degree Engineer",
        description="I am a software engineer with over 10 years of experience in web development. I have a strong background in JavaScript, TypeScript, and various frameworks such as React and Angular.  I'm passionate about building scalable and maintainable applications I like to imagine and creating proposals for different projects. I started as a young Freelance Developer and later evolved into a young entrepreneur leading my own development team, working mostly for a International Logistics and Trade Company based on Veracruz city, called Grupo CICE, as one of their main mobile develpment providers.  In a not so long future I want to become a Software Architech",
    )
    session.add(profile)
    return profile


def add_languages(session):
    languages = [
        Language(language="Spanish", level="Native"),
        Language(language="English", level="Fluent"),
    ]
    session.add_all(languages)


def add_project_categories(session):
    project_category_dict: dict[
        Literal[
            "App",
            "Web",
            "Projects",
            "Branding",
            "Backend",
            "Frontend",
            "Fullstack",
            "Mobile",
        ],
        ProjectCategory,
    ] = {
        "App": ProjectCategory(name="App"),
        "Web": ProjectCategory(name="Web"),
        "Projects": ProjectCategory(name="Projects"),
        "Branding": ProjectCategory(name="Branding"),
        "Backend": ProjectCategory(name="Backend"),
        "Frontend": ProjectCategory(name="Frontend"),
        "Fullstack": ProjectCategory(name="Fullstack"),
        "Mobile": ProjectCategory(name="Mobile"),
    }

    session.add_all(list(project_category_dict.values()))
    return project_category_dict


def add_skills(session):
    # Now use SkillNames as the key type
    skill_dict: dict[SkillNames, Skill] = {
        "Technical Support": Skill(
            skill="Technical Support", level=80, firstUsedDate=date(2023, 1, 1)
        ),
        "Prisma ORM": Skill(
            skill="Prisma ORM", level=50, firstUsedDate=date(2023, 1, 1)
        ),
        "Adobe Flex": Skill(
            skill="Adobe Flex", level=90, firstUsedDate=date(2010, 1, 1)
        ),
        "dask": Skill(skill="Dask", level=60, firstUsedDate=date(2024, 12, 1)),
        "alembic": Skill(skill="Alembic", level=70, firstUsedDate=date(2024, 12, 1)),
        "Ionic": Skill(skill="Ionic", level=80, firstUsedDate=date(2010, 1, 1)),
        "Yeoman": Skill(skill="Yeoman", level=70, firstUsedDate=date(2010, 1, 1)),
        "PhoneGap": Skill(skill="PhoneGap", level=80, firstUsedDate=date(2010, 1, 1)),
        "Cordova": Skill(skill="Cordova", level=80, firstUsedDate=date(2010, 1, 1)),
        "Adobe AIR": Skill(skill="Adobe AIR", level=90, firstUsedDate=date(2010, 1, 1)),
        "Python": Skill(skill="Python", level=60, firstUsedDate=date(2022, 1, 1)),
        "HTML": Skill(skill="HTML", level=70, firstUsedDate=date(2009, 1, 1)),
        "CSS/SCSS": Skill(skill="CSS/SCSS", level=70, firstUsedDate=date(2011, 1, 1)),
        "Tailwind CSS": Skill(
            skill="Tailwind CSS", level=10, firstUsedDate=date(2025, 3, 1)
        ),
        "Javascript": Skill(
            skill="Javascript", level=80, firstUsedDate=date(2011, 1, 1)
        ),
        "Typescript": Skill(
            skill="Typescript", level=80, firstUsedDate=date(2012, 1, 1)
        ),
        "React": Skill(skill="React", level=80, firstUsedDate=date(2020, 1, 1)),
        "SOLID_principles": Skill(
            skill="SOLID principles", level=80, firstUsedDate=date(2020, 1, 1)
        ),
        "Storybook": Skill(skill="Storybook", level=50, firstUsedDate=date(2018, 1, 1)),
        "Angular": Skill(skill="Angular", level=80, firstUsedDate=date(2013, 1, 1)),
        "Material Design": Skill(
            skill="Material Design", level=80, firstUsedDate=date(2014, 7, 1)
        ),
        "Express.js": Skill(
            skill="Express.js", level=80, firstUsedDate=date(2017, 1, 1)
        ),
        "Node.js": Skill(skill="Node.js", level=80, firstUsedDate=date(2015, 1, 1)),
        "MongoDB": Skill(skill="MongoDB", level=70, firstUsedDate=date(2017, 1, 1)),
        "PostgreSQL": Skill(
            skill="PostgreSQL", level=70, firstUsedDate=date(2017, 1, 1)
        ),
        "MySQL": Skill(skill="MySQL", level=70, firstUsedDate=date(2009, 1, 1)),
        "Bootstrap": Skill(skill="Bootstrap", level=80, firstUsedDate=date(2015, 1, 1)),
        "Git": Skill(skill="Git", level=80, firstUsedDate=date(2011, 1, 1)),
        "Domain Driven Design": Skill(
            skill="Domain Driven Design", level=75, firstUsedDate=date(2023, 1, 1)
        ),
        "Docker": Skill(skill="Docker", level=30, firstUsedDate=date(2023, 1, 1)),
        "Microservices": Skill(
            skill="Microservices", level=70, firstUsedDate=date(2018, 1, 1)
        ),
        "REST Services": Skill(
            skill="REST Services", level=70, firstUsedDate=date(2018, 1, 1)
        ),
        "GraphQL": Skill(skill="GraphQL", level=50, firstUsedDate=date(2022, 1, 1)),
        "Figma": Skill(skill="Figma", level=50, firstUsedDate=date(2022, 1, 1)),
        "Redux": Skill(skill="Redux", level=50, firstUsedDate=date(2018, 1, 1)),
        "CI/CD": Skill(skill="CI/CD", level=50, firstUsedDate=date(2018, 1, 1)),
        "Jira": Skill(skill="Jira", level=50, firstUsedDate=date(2018, 1, 1)),
        "UML": Skill(skill="UML", level=70, firstUsedDate=date(2009, 1, 1)),
        "Design Patterns": Skill(
            skill="Design Patterns", level=75, firstUsedDate=date(2018, 1, 1)
        ),
        "OOP": Skill(skill="OOP", level=90, firstUsedDate=date(2018, 1, 1)),
        "Android Development": Skill(
            skill="Android Development", level=50, firstUsedDate=date(2015, 1, 1)
        ),
        "ActionScript 3.0": Skill(
            skill="ActionScript 3.0", level=90, firstUsedDate=date(2010, 1, 1)
        ),
        "FastAPI": Skill(skill="FastAPI", level=70, firstUsedDate=date(2024, 1, 1)),
        "Django": Skill(skill="Django", level=20, firstUsedDate=date(2024, 1, 1)),
        "Testing": Skill(skill="Testing", level=60, firstUsedDate=date(2024, 1, 1)),
        "Next.js": Skill(skill="Next.js", level=50, firstUsedDate=date(2020, 1, 1)),
        "NestJs": Skill(skill="NestJs", level=60, firstUsedDate=date(2020, 1, 1)),
        "TypeOrm": Skill(skill="TypeOrm", level=60, firstUsedDate=date(2020, 1, 1)),
        "Technical Documentation": Skill(
            skill="Technical Documentation", level=80, firstUsedDate=date(2012, 1, 1)
        ),
        "Firebase": Skill(skill="Firebase", level=50, firstUsedDate=date(2016, 1, 1)),
        "Render": Skill(skill="Render", level=50, firstUsedDate=date(2025, 8, 1)),
        "Supabase": Skill(skill="Supabase", level=50, firstUsedDate=date(2025, 8, 1)),
        "Github Actions": Skill(
            skill="Github Actions", level=50, firstUsedDate=date(2025, 1, 1)
        ),
        "Github Pages": Skill(
            skill="Github Pages", level=50, firstUsedDate=date(2025, 1, 1)
        ),
        "UI/UX": Skill(skill="UI/UX", level=50, firstUsedDate=date(2010, 1, 1)),
        "Azure": Skill(skill="Azure", level=50, firstUsedDate=date(2020, 1, 1)),
        "DynamoDB": Skill(skill="DynamoDB", level=50, firstUsedDate=date(2018, 1, 1)),
        "Postman": Skill(skill="Postman", level=80, firstUsedDate=date(2018, 1, 1)),
        "AWS": Skill(skill="AWS", level=50, firstUsedDate=date(2018, 1, 1)),
        "Wordpress": Skill(skill="Wordpress", level=50, firstUsedDate=date(2014, 1, 1)),
        "PHP": Skill(skill="PHP", level=50, firstUsedDate=date(2014, 1, 1)),
        "Scrum": Skill(skill="Scrum", level=90, firstUsedDate=date(2014, 1, 1)),
        "Kanban": Skill(skill="Kanban", level=90, firstUsedDate=date(2014, 1, 1)),
        "Clean Architecture": Skill(
            skill="Clean Architecture", level=80, firstUsedDate=date(2020, 1, 1)
        ),
        "Metaio framework": Skill(
            skill="Metaio framework", level=80, firstUsedDate=date(2015, 1, 1)
        ),
        "Socket.io": Skill(skill="Socket.io", level=80, firstUsedDate=date(2017, 1, 1)),
        "event_driven_architecture": Skill(
            skill="Event Driven Architecture", level=80, firstUsedDate=date(2017, 1, 1)
        ),
        "Pm2": Skill(skill="Pm2", level=80, firstUsedDate=date(2018, 1, 1)),
        "world_wind": Skill(
            skill="World Wind", level=40, firstUsedDate=date(2017, 1, 1)
        ),
        "GIS": Skill(
            skill="Geographic Information System",
            level=40,
            firstUsedDate=date(2017, 1, 1),
        ),
        "Adobe Illustrator": Skill(
            skill="Adobe Illustrator", level=80, firstUsedDate=date(2000, 1, 1)
        ),
        "Adobe InDesign": Skill(
            skill="Adobe Illustrator", level=80, firstUsedDate=date(2000, 1, 1)
        ),
        "Adobe Photoshop": Skill(
            skill="Adobe Photoshop", level=80, firstUsedDate=date(1999, 1, 1)
        ),
        "Robotlegs": Skill(skill="Robotlegs", level=80, firstUsedDate=date(2008, 1, 1)),
        "RxJS Observables": Skill(
            skill="RxJS Observables", level=80, firstUsedDate=date(2014, 1, 1)
        ),
        "Java": Skill(skill="Java", level=50, firstUsedDate=date(2008, 1, 1)),
        "SQLModel": Skill(skill="SQLModel", level=70, firstUsedDate=date(2024, 1, 1)),
        "PySide6": Skill(skill="PySide6", level=70, firstUsedDate=date(2024, 1, 1)),
        "numpy": Skill(skill="numpy", level=50, firstUsedDate=date(2024, 1, 1)),
        "matplotlib": Skill(skill="matplotlib", level=50, firstUsedDate=date(2024, 1, 1)),
        "pandas": Skill(skill="pandas", level=50, firstUsedDate=date(2024, 1, 1)),
        "Augmented Reality": Skill(
            skill="Augmented Reality", level=50, firstUsedDate=date(2015, 1, 1)
        ),
    }

    skills: list[Skill] = list(skill_dict.values())
    session.add_all(skills)
    return skill_dict


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    session = Session(bind=bind)
    statement = select(Skill)
    all_skills = session.exec(statement).all()
    for skill in all_skills:
        session.delete(skill)
    session.commit()
    table_object = Skill.__table__  # type: ignore
    table_object.drop(bind=op.get_bind())
