"""project model added and project category added

Revision ID: bf408f67b52c
Revises: 3c6ca54f6349
Create Date: 2025-08-11 01:15:45.636810

"""
from typing import Sequence, Union

from alembic import op
from sqlmodel import Session, select

from src.project.infrastructure.models.project_category_model import ProjectCategory


# revision identifiers, used by Alembic.
revision: str = 'bf408f67b52c'
down_revision: Union[str, Sequence[str], None] = '3c6ca54f6349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


cat_list =["Apps" , "Web" , "Projects"  , "Branding", 'Personal']

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    cats= [ProjectCategory(name=item) for item in cat_list]
    # ### end Alembic commands ###
    with Session(bind=op.get_bind()) as session :
        session.add_all(cats)
        session.commit()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    statement = select(ProjectCategory)
    with Session(bind=op.get_bind()) as session :
        cats=session.exec(statement).all()
        for cat in cats:
            session.delete(cat)
        session.commit()
    # ### end Alembic commands ###
