"""add new relationship between professional experience and project 

Revision ID: db5a482b123c
Revises: 1d0c0cb1672d
Create Date: 2025-08-15 16:03:02.655896

"""
from typing import Sequence, Union

from alembic import op
from src.project.infrastructure.models import Project
from src.professional_experience.infrastructure.models import ProfessionalExperience ,Responsibility



# revision identifiers, used by Alembic.
revision: str = 'db5a482b123c'
down_revision: Union[str, Sequence[str], None] = '1d0c0cb1672d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_table('project')
        op.drop_table('professionalexperienceskilllink')
        op.drop_table('professional_experience')
        op.drop_table('responsibility')
        
        
    except Exception:
        print('tried to delete table')
    
    
    try:
        table_obj=Project.__table__ # type: ignore
        table_obj.create(bind=op.get_bind())
        
        table_obj=ProfessionalExperience.__table__ # type: ignore
        table_obj.create(bind=op.get_bind())

        table_obj=Responsibility.__table__ # type: ignore
        table_obj.create(bind=op.get_bind())
    except Exception as e:
        print('Could not create the tables',e)
    
    
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_table('professionalexperienceskilllink')
        op.drop_table('professional_experience')
        op.drop_table('project')
        op.drop_table('responsibility')
        
        
    except Exception:
        print('tried to delete table')

