"""generate profile table

Revision ID: f36ea99a2918
Revises: 0a54bfc6ea6e
Create Date: 2025-08-03 16:42:09.414377

"""

from datetime import date
from typing import Sequence, Union

from alembic import op
from sqlmodel import Session, select

from src.profile.infrastructure.models import Profile


# revision identifiers, used by Alembic.
revision: str = "f36ea99a2918"
down_revision: Union[str, Sequence[str], None] = "0a54bfc6ea6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        table_obj=Profile.__table__  # type: ignore
        table_obj.create(bind=op.get_bind())
    except Exception:
        print(Exception)
    finally:
        me = Profile(
            name="Mario Rivera",
            birthday=date(day=10, month=11, year=1986),
            phone="+52 229-148-6661",
            city="Veracruz, Veracruz",
            degree="Engineer",
            description="about.description",
            email="ace.mrivera@gmail.com",
            freelance="Available",
        )
        with Session(bind=op.get_bind()) as session :
            session.add(me)
            session.commit()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    statement = select(Profile).where( Profile.name =="Mario Rivera", Profile.birthday == date(day=10, month=11, year=1986))
    
    with Session(bind=op.get_bind()) as session :
        me =session.exec(statement).first()
        session.delete(me)
        session.commit()
    table_object=Profile.__table__ # type: ignore
    table_object.drop(bind=op.get_bind())
    # ### end Alembic commands ###
